parser: '@typescript-eslint/parser'
plugins:
  - solid
extends:
  - eslint:recommended
  - plugin:solid/typescript
  - plugin:astro/recommended
  - prettier
overrides:
  - files:
      - '*.astro'
    parser: astro-eslint-parser
    parserOptions:
      parser: '@typescript-eslint/parser'
      extraFileExtensions:
        - '.astro'
